services:
  kali:
    image: kali_attacker
    container_name: attacker
    tty: true
    stdin_open: true
    #Running in privileged mode to conduct reconnaisance with nmap.
    privileged: true
    command: ["/bin/bash", "-c", "service ssh start && tail -f /dev/null"]
    networks:
      - ctf_network
    ports:
      - 2222:22

  ubuntu:
    image: ubuntu_victim
    container_name: victim
    tty: true
    stdin_open: true
    command: ["/bin/bash", "-c", "service ssh start && service apache2 start && tail -f /dev/null"]
    networks:
      - ctf_network
    ports:
      - 8080:80
      - 2223:22

  ctfd:
    image: ctfd_v1
    container_name: ctfd
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - ctf_network
    environment:
      - CTF_NAME=Cyber Gauntlet CTF
      - SECRET_KEY=mysecretkey
      - DATABASE_URL=sqlite:///ctfd.db
    volumes:
      - ctfd_data:/var/www/ctfd

volumes:
  ctfd_data:
networks:
  ctf_network:
    driver: bridge
